title: Saurav's Blog
description: Thinking in systems, patterns, and first principles.
url: https://saurav-malani.github.io
baseurl: /blog
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
permalink: /:slug/
author_email: sauravmalani1@gmail.com
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
